export const colors = {
    background: "#F4F3F8",
    foreground: "#1A1830",
    card: "#FFFFFF",
    cardForeground: "#1A1830",
    primary: "#2D2560",
    primaryForeground: "#FAFAFA",
    secondary: "#F0EEF8",
    muted: "#ECEAF4",
    mutedForeground: "#6B6585",
    accent: "#D946A8",
    accentForeground: "#FAFAFA",
    destructive: "#DC2626",
    destructiveForeground: "#FAFAFA",
    border: "#E4E2EE",
    input: "#E4E2EE",
    ring: "#D946A8",
    gradientStart: "#D946A8",
    gradientEnd: "#7C3AED",
};
